version: "3.8"

name: tp-node-pdf
services:
  app:
    container_name: frontend 
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    env_file:
      - .env
