version: "3.8"
  


services:
  backend:
    build: 
      context: backend 
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "1010:1010"
    volumes:
      - ./backend:/app
     # - ./backend/node_modules:/app/node_modules
      - node_modules_back:/app/node_modules
      - ./frontend:/app/db
  frontend:
    build: 
      context: frontend 
      dockerfile: Dockerfile
    container_name: front-container
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
     # - ./backend/node_modules:/app/node_modules
      - node_modules_front:/app/node_modules
volumes:
  node_modules_back:
  node_modules_front:
