version: '3'
  

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tp-node-pdf
    ports:
      - 5433:5432
    volumes:
      - tp_node_postgres_data:/var/lib/postgresql/data/

volumes:
  tp_node_postgres_data: