version: '3'
  

services:
  web:
    build: .
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "1010:1010"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tp-node-pdf
    ports:
      - 5433:5432
    volumes:
      - tp_node_postgres_data:/var/lib/postgresql/data/

volumes:
  tp_node_postgres_data:
